version: "3.8"

services:
  web:
    image: nginx:alpine
    container_name: sub
    restart: unless-stopped
    networks:
      - vpn_net
    volumes:
      - ./html:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sub.rule=Host(`sub.edusnapec.online`)"
      - "traefik.http.routers.sub.entrypoints=http"
      - "traefik.http.routers.sub.middlewares=redirect-to-https"
      - "traefik.http.routers.sub-secure.rule=Host(`sub.edusnapec.online`)"
      - "traefik.http.routers.sub-secure.entrypoints=https"
      - "traefik.http.routers.sub-secure.tls=true"
      - "traefik.http.routers.sub-secure.tls.certresolver=cloudflare"
      - "traefik.http.services.sub.loadbalancer.server.port=80"

networks:
  vpn_net:
    external: true
